# Generated by Django 4.2.9 on 2024-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=50)),
                ("description", models.TextField(default=None)),
                ("svg", models.TextField(default=None)),
                ("use_case", models.CharField(default=None, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        default="free",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
