# Generated by Django 4.2.9 on 2024-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0003_category_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="sub_catagory",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
