# Generated by Django 4.2.9 on 2024-05-06 11:53

from django.db import migrations, models
import django.db.models.deletion
import gbtapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0004_subcategory_sub_catagory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=gbtapp.models.generate_unique_id,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("botname", models.CharField(max_length=50)),
                ("system_prompt", models.CharField(max_length=50)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gbtapp.category",
                    ),
                ),
            ],
        ),
    ]
