# Generated by Django 4.2.9 on 2024-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0006_alter_botrecord_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botrecord",
            name="botname",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="botrecord",
            name="system_prompt",
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
