# Generated by Django 4.2.9 on 2024-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0007_alter_botrecord_botname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botrecord",
            name="system_prompt",
            field=models.TextField(),
        ),
    ]
