# Generated by Django 4.2.9 on 2024-05-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbtapp", "0009_botrecord_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botrecord",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
